export const actionTypes = {
	FETCH_ACCOUNTS: 'TRANSACTIONS/FETCH_ACCOUNTS',
	FETCH_ACCOUNTS_SUCCESS: 'TRANSACTIONS/FETCH_ACCOUNTS_SUCCESS',
	FETCH_ACCOUNTS_FAILURE: 'TRANSACTIONS/FETCH_ACCOUNTS_FAILURE',
	FETCH_TRANSACTIONS: 'TRANSACTIONS/FETCH_TRANSACTIONS',
	FETCH_TRANSACTIONS_SUCCESS: 'TRANSACTIONS/FETCH_TRANSACTIONS_SUCCESS',
	FETCH_TRANSACTIONS_FAILURE: 'TRANSACTIONS/FETCH_TRANSACTIONS_FAILURE'
};