export const actionTypes = {
	ADD_NEW_FILTER: 'TRANSACTIONS/ADD_NEW_FILTER',

	FETCH_ACCOUNTS: 'TRANSACTIONS/FETCH_ACCOUNTS',
	FETCH_ACCOUNTS_SUCCESS: 'TRANSACTIONS/FETCH_ACCOUNTS_SUCCESS',
	FETCH_ACCOUNTS_FAILURE: 'TRANSACTIONS/FETCH_ACCOUNTS_FAILURE',

	FETCH_CATEGORIES: 'TRANSACTIONS/FETCH_CATEGORIES',
	FETCH_CATEGORIES_SUCCESS: 'TRANSACTIONS/FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_FAILURE: 'TRANSACTIONS/FETCH_CATEGORIES_FAILURE',

	FETCH_TRANSACTIONS: 'TRANSACTIONS/FETCH_TRANSACTIONS',
	FETCH_TRANSACTIONS_SUCCESS: 'TRANSACTIONS/FETCH_TRANSACTIONS_SUCCESS',
	FETCH_TRANSACTIONS_FAILURE: 'TRANSACTIONS/FETCH_TRANSACTIONS_FAILURE',

	TOGGLE_CATEGORY: 'TRANSACTIONS/TOGGLE_CATEGORY'
};